# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._open_supply_chain_platform_service_api import OpenSupplyChainPlatformServiceAPI
__all__ = ['OpenSupplyChainPlatformServiceAPI']
