# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AccessAssignment
    from ._models_py3 import AttributeCondition
    from ._models_py3 import ResourceOfShare
    from ._models_py3 import ResourceOfWorkspace
    from ._models_py3 import Share
    from ._models_py3 import Workspace
except (SyntaxError, ImportError):
    from ._models import AccessAssignment  # type: ignore
    from ._models import AttributeCondition  # type: ignore
    from ._models import ResourceOfShare  # type: ignore
    from ._models import ResourceOfWorkspace  # type: ignore
    from ._models import Share  # type: ignore
    from ._models import Workspace  # type: ignore

__all__ = [
    'AccessAssignment',
    'AttributeCondition',
    'ResourceOfShare',
    'ResourceOfWorkspace',
    'Share',
    'Workspace',
]
