# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import msrest.serialization


class AccessAssignment(msrest.serialization.Model):
    """AccessAssignment.

    :param action_ids:
    :type action_ids: list[str]
    :param attribute_conditions:
    :type attribute_conditions: list[~oscp.controlplane.models.AttributeCondition]
    """

    _attribute_map = {
        'action_ids': {'key': 'actionIds', 'type': '[str]'},
        'attribute_conditions': {'key': 'attributeConditions', 'type': '[AttributeCondition]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(AccessAssignment, self).__init__(**kwargs)
        self.action_ids = kwargs.get('action_ids', None)
        self.attribute_conditions = kwargs.get('attribute_conditions', None)


class AttributeCondition(msrest.serialization.Model):
    """AttributeCondition.

    :param attribute_name:
    :type attribute_name: str
    :param values:
    :type values: list[str]
    :param attribute_matching_scheme:
    :type attribute_matching_scheme: str
    """

    _attribute_map = {
        'attribute_name': {'key': 'attributeName', 'type': 'str'},
        'values': {'key': 'values', 'type': '[str]'},
        'attribute_matching_scheme': {'key': 'attributeMatchingScheme', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(AttributeCondition, self).__init__(**kwargs)
        self.attribute_name = kwargs.get('attribute_name', None)
        self.values = kwargs.get('values', None)
        self.attribute_matching_scheme = kwargs.get('attribute_matching_scheme', None)


class ResourceOfShare(msrest.serialization.Model):
    """ResourceOfShare.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param type:
    :type type: str
    :param location:
    :type location: str
    :param e_tag:
    :type e_tag: str
    :param tags: A set of tags. The insensitive version of dictionary.
    :type tags: dict[str, str]
    :param properties:
    :type properties: ~oscp.controlplane.models.Share
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'e_tag': {'key': 'eTag', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': 'Share'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ResourceOfShare, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.type = kwargs.get('type', None)
        self.location = kwargs.get('location', None)
        self.e_tag = kwargs.get('e_tag', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)


class ResourceOfWorkspace(msrest.serialization.Model):
    """ResourceOfWorkspace.

    :param id:
    :type id: str
    :param name:
    :type name: str
    :param type:
    :type type: str
    :param location:
    :type location: str
    :param e_tag:
    :type e_tag: str
    :param tags: A set of tags. The insensitive version of dictionary.
    :type tags: dict[str, str]
    :param properties:
    :type properties: ~oscp.controlplane.models.Workspace
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'e_tag': {'key': 'eTag', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': 'Workspace'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ResourceOfWorkspace, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.type = kwargs.get('type', None)
        self.location = kwargs.get('location', None)
        self.e_tag = kwargs.get('e_tag', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)


class Share(msrest.serialization.Model):
    """Share.

    All required parameters must be populated in order to send to Azure.

    :param share_id: Gets or sets shareId.
    :type share_id: str
    :param share_name: Gets or sets the share Name.
    :type share_name: str
    :param description: Gets or sets the share description.
    :type description: str
    :param source_tenant_id:
    :type source_tenant_id: str
    :param target_tenant_id: Required. Gets or sets the Target TenantId.
    :type target_tenant_id: str
    :param share_state: Gets or sets the state.
    :type share_state: str
    :param access_assignments: Gets or sets the accessAssignments.
    :type access_assignments: list[~oscp.controlplane.models.AccessAssignment]
    """

    _validation = {
        'share_name': {'max_length': 512, 'min_length': 0},
        'description': {'max_length': 512, 'min_length': 0},
        'target_tenant_id': {'required': True, 'min_length': 1},
    }

    _attribute_map = {
        'share_id': {'key': 'shareId', 'type': 'str'},
        'share_name': {'key': 'shareName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'source_tenant_id': {'key': 'sourceTenantId', 'type': 'str'},
        'target_tenant_id': {'key': 'targetTenantId', 'type': 'str'},
        'share_state': {'key': 'shareState', 'type': 'str'},
        'access_assignments': {'key': 'accessAssignments', 'type': '[AccessAssignment]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(Share, self).__init__(**kwargs)
        self.share_id = kwargs.get('share_id', None)
        self.share_name = kwargs.get('share_name', None)
        self.description = kwargs.get('description', None)
        self.source_tenant_id = kwargs.get('source_tenant_id', None)
        self.target_tenant_id = kwargs['target_tenant_id']
        self.share_state = kwargs.get('share_state', None)
        self.access_assignments = kwargs.get('access_assignments', None)


class Workspace(msrest.serialization.Model):
    """Workspace.

    :param workspace_id: The workspace Id.
    :type workspace_id: str
    :param provisioning_state: The provisioning state.
    :type provisioning_state: str
    :param share_id: Gets or sets the Share Id for projected Resource.
    :type share_id: str
    :param workspace_url: The Workspace Url.
    :type workspace_url: str
    """

    _validation = {
        'workspace_id': {'max_length': 128, 'min_length': 0},
    }

    _attribute_map = {
        'workspace_id': {'key': 'workspaceId', 'type': 'str'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'share_id': {'key': 'shareId', 'type': 'str'},
        'workspace_url': {'key': 'workspaceUrl', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(Workspace, self).__init__(**kwargs)
        self.workspace_id = kwargs.get('workspace_id', None)
        self.provisioning_state = kwargs.get('provisioning_state', None)
        self.share_id = kwargs.get('share_id', None)
        self.workspace_url = kwargs.get('workspace_url', None)
