# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum, EnumMeta
from six import with_metaclass

class _CaseInsensitiveEnumMeta(EnumMeta):
    def __getitem__(self, name):
        return super().__getitem__(name.upper())

    def __getattr__(cls, name):
        """Return the enum member matching `name`
        We use __getattr__ instead of descriptors or inserting into the enum
        class' __dict__ in order to support `name` and `value` being both
        properties for enum members (which live in the class' __dict__) and
        enum members themselves.
        """
        try:
            return cls._member_map_[name.upper()]
        except KeyError:
            raise AttributeError(name)


class HostOptions(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """choices for server host
    """

    #: host: https://7ab4ba6c-ffd5-4790-85ce-2d0f63d33750-workspace.supplychain.azure-test.net/.
    HTTPS7_AB4_BA6_C_FFD5_4790_85_CE2_D0_F63_D33750_WORKSPACE_SUPPLYCHAIN_AZURE_TEST_NET_ = "https://7ab4ba6c-ffd5-4790-85ce-2d0f63d33750-workspace.supplychain.azure-test.net/"
    #: host: http://7ab4ba6c-ffd5-4790-85ce-2d0f63d33750-workspace.supplychain.azure-test.net/.
    HTTP7_AB4_BA6_C_FFD5_4790_85_CE2_D0_F63_D33750_WORKSPACE_SUPPLYCHAIN_AZURE_TEST_NET_ = "http://7ab4ba6c-ffd5-4790-85ce-2d0f63d33750-workspace.supplychain.azure-test.net/"
