# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from typing import Any, Callable, Dict, Generic, List, Optional, TypeVar, Union
import warnings

from azure.core.exceptions import ClientAuthenticationError, HttpResponseError, ResourceExistsError, ResourceNotFoundError, map_error
from azure.core.pipeline import PipelineResponse
from azure.core.pipeline.transport import AsyncHttpResponse, HttpRequest

from ... import models as _models

T = TypeVar('T')
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, Dict[str, Any]], Any]]

class FulfillmentPlanOperations:
    """FulfillmentPlanOperations async operations.

    You should not instantiate this class directly. Instead, you should create a Client instance that
    instantiates it for you and attaches it as an attribute.

    :ivar models: Alias to model classes used in this operation group.
    :type models: ~oscp.dataplane.models
    :param client: Client for service requests.
    :param config: Configuration of service client.
    :param serializer: An object model serializer.
    :param deserializer: An object model deserializer.
    """

    models = _models

    def __init__(self, client, config, serializer, deserializer) -> None:
        self._client = client
        self._serialize = serializer
        self._deserialize = deserializer
        self._config = config

    async def get_plan(
        self,
        fulfillment_plan_id: str,
        **kwargs
    ) -> "_models.FulfillmentPlan":
        """Retrieves the fulfillment plan for given workspace ID and fulfillment plan ID.

        Retrieves the fulfillment plan for given workspace ID and fulfillment plan ID.

        :param fulfillment_plan_id: The fulfillment plane identifier.
        :type fulfillment_plan_id: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: FulfillmentPlan, or the result of cls(response)
        :rtype: ~oscp.dataplane.models.FulfillmentPlan
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["_models.FulfillmentPlan"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        accept = "application/json, text/json"

        # Construct URL
        url = self.get_plan.metadata['url']  # type: ignore
        path_format_arguments = {
            'fulfillmentPlanId': self._serialize.url("fulfillment_plan_id", fulfillment_plan_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.get(url, query_parameters, header_parameters)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize('FulfillmentPlan', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    get_plan.metadata = {'url': '/fulfillmentPlans/{fulfillmentPlanId}'}  # type: ignore

    async def update_plan(
        self,
        fulfillment_plan_id: str,
        plan: "_models.FulfillmentPlan",
        **kwargs
    ) -> Union["_models.FulfillmentPlan", "_models.ErrorObject"]:
        """Updates a fulfillment plan given workspace ID, fulfillment plan ID and fulfillment plan payload.

        Updates a fulfillment plan given workspace ID, fulfillment plan ID and fulfillment plan
        payload.

        :param fulfillment_plan_id: The fulfillment plan identifier.
        :type fulfillment_plan_id: str
        :param plan: The fulfillment plan to be updated.
        :type plan: ~oscp.dataplane.models.FulfillmentPlan
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: FulfillmentPlan or ErrorObject, or the result of cls(response)
        :rtype: ~oscp.dataplane.models.FulfillmentPlan or ~oscp.dataplane.models.ErrorObject
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[Union["_models.FulfillmentPlan", "_models.ErrorObject"]]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json, text/json"

        # Construct URL
        url = self.update_plan.metadata['url']  # type: ignore
        path_format_arguments = {
            'fulfillmentPlanId': self._serialize.url("fulfillment_plan_id", fulfillment_plan_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(plan, 'FulfillmentPlan')
        body_content_kwargs['content'] = body_content
        request = self._client.patch(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200, 449]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        if response.status_code == 200:
            deserialized = self._deserialize('FulfillmentPlan', pipeline_response)

        if response.status_code == 449:
            response_headers['x-ms-retry-after-ms']=self._deserialize('int', response.headers.get('x-ms-retry-after-ms'))
            deserialized = self._deserialize('ErrorObject', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, response_headers)

        return deserialized
    update_plan.metadata = {'url': '/fulfillmentPlans/{fulfillmentPlanId}'}  # type: ignore

    async def get_plans(
        self,
        warehouse_id: Optional[str] = None,
        status: Optional[str] = None,
        **kwargs
    ) -> List["_models.FulfillmentPlan"]:
        """Retrieves a list of fulfillment plans with specifica fulfillment status for given workspace ID and warehouse ID.

        Retrieves a list of fulfillment plans with specifica fulfillment status for given workspace ID
        and warehouse ID.

        :param warehouse_id: The warehouse identifier.
        :type warehouse_id: str
        :param status: The fulfillment status.
        :type status: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: list of FulfillmentPlan, or the result of cls(response)
        :rtype: list[~oscp.dataplane.models.FulfillmentPlan]
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[List["_models.FulfillmentPlan"]]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        accept = "application/json, text/json"

        # Construct URL
        url = self.get_plans.metadata['url']  # type: ignore

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        if warehouse_id is not None:
            query_parameters['warehouseId'] = self._serialize.query("warehouse_id", warehouse_id, 'str')
        if status is not None:
            query_parameters['status'] = self._serialize.query("status", status, 'str')
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.get(url, query_parameters, header_parameters)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize('[FulfillmentPlan]', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    get_plans.metadata = {'url': '/fulfillmentPlans'}  # type: ignore
