# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.2.1, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from typing import Any, Callable, Dict, Generic, IO, List, Optional, TypeVar, Union
import warnings

from azure.core.exceptions import ClientAuthenticationError, HttpResponseError, ResourceExistsError, ResourceNotFoundError, map_error
from azure.core.pipeline import PipelineResponse
from azure.core.pipeline.transport import AsyncHttpResponse, HttpRequest

from ... import models as _models

T = TypeVar('T')
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, Dict[str, Any]], Any]]

class WarehouseItemOperations:
    """WarehouseItemOperations async operations.

    You should not instantiate this class directly. Instead, you should create a Client instance that
    instantiates it for you and attaches it as an attribute.

    :ivar models: Alias to model classes used in this operation group.
    :type models: ~oscp.dataplane.models
    :param client: Client for service requests.
    :param config: Configuration of service client.
    :param serializer: An object model serializer.
    :param deserializer: An object model deserializer.
    """

    models = _models

    def __init__(self, client, config, serializer, deserializer) -> None:
        self._client = client
        self._serialize = serializer
        self._deserialize = deserializer
        self._config = config

    async def get(
        self,
        warehouse_id: str,
        item_sku: str,
        **kwargs
    ) -> "_models.WarehouseItem":
        """get.

        :param warehouse_id:
        :type warehouse_id: str
        :param item_sku:
        :type item_sku: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: WarehouseItem, or the result of cls(response)
        :rtype: ~oscp.dataplane.models.WarehouseItem
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType["_models.WarehouseItem"]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        accept = "application/json, text/json"

        # Construct URL
        url = self.get.metadata['url']  # type: ignore
        path_format_arguments = {
            'warehouseId': self._serialize.url("warehouse_id", warehouse_id, 'str'),
            'itemSKU': self._serialize.url("item_sku", item_sku, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.get(url, query_parameters, header_parameters)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize('WarehouseItem', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    get.metadata = {'url': '/warehouses/{warehouseId}/warehouseItems/{itemSKU}'}  # type: ignore

    async def put(
        self,
        warehouse_id: str,
        item_sku: str,
        warehouse_item: "_models.WarehouseItem",
        **kwargs
    ) -> Union["_models.WarehouseItem", "_models.ErrorObject"]:
        """put.

        :param warehouse_id:
        :type warehouse_id: str
        :param item_sku:
        :type item_sku: str
        :param warehouse_item:
        :type warehouse_item: ~oscp.dataplane.models.WarehouseItem
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: WarehouseItem or ErrorObject, or the result of cls(response)
        :rtype: ~oscp.dataplane.models.WarehouseItem or ~oscp.dataplane.models.ErrorObject
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[Union["_models.WarehouseItem", "_models.ErrorObject"]]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json, text/json"

        # Construct URL
        url = self.put.metadata['url']  # type: ignore
        path_format_arguments = {
            'warehouseId': self._serialize.url("warehouse_id", warehouse_id, 'str'),
            'itemSKU': self._serialize.url("item_sku", item_sku, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(warehouse_item, 'WarehouseItem')
        body_content_kwargs['content'] = body_content
        request = self._client.put(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200, 449]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        if response.status_code == 200:
            deserialized = self._deserialize('WarehouseItem', pipeline_response)

        if response.status_code == 449:
            response_headers['x-ms-retry-after-ms']=self._deserialize('int', response.headers.get('x-ms-retry-after-ms'))
            deserialized = self._deserialize('ErrorObject', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, response_headers)

        return deserialized
    put.metadata = {'url': '/warehouses/{warehouseId}/warehouseItems/{itemSKU}'}  # type: ignore

    async def delete(
        self,
        warehouse_id: str,
        item_sku: str,
        **kwargs
    ) -> IO:
        """delete.

        :param warehouse_id:
        :type warehouse_id: str
        :param item_sku:
        :type item_sku: str
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: IO, or the result of cls(response)
        :rtype: IO
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[IO]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        accept = "text/plain, application/json, text/json"

        # Construct URL
        url = self.delete.metadata['url']  # type: ignore
        path_format_arguments = {
            'warehouseId': self._serialize.url("warehouse_id", warehouse_id, 'str'),
            'itemSKU': self._serialize.url("item_sku", item_sku, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        request = self._client.delete(url, query_parameters, header_parameters)
        pipeline_response = await self._client._pipeline.run(request, stream=True, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200, 200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if response.status_code == 200:
            deserialized = self._deserialize('IO', pipeline_response)

        if response.status_code == 200:
            deserialized = self._deserialize('IO', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    delete.metadata = {'url': '/warehouses/{warehouseId}/warehouseItems/{itemSKU}'}  # type: ignore

    async def bulk_put(
        self,
        warehouse_id: str,
        warehouse_items: List["_models.WarehouseItem"],
        **kwargs
    ) -> List["_models.BulkResponseItemOfWarehouseItem"]:
        """bulk_put.

        :param warehouse_id:
        :type warehouse_id: str
        :param warehouse_items:
        :type warehouse_items: list[~oscp.dataplane.models.WarehouseItem]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: list of BulkResponseItemOfWarehouseItem, or the result of cls(response)
        :rtype: list[~oscp.dataplane.models.BulkResponseItemOfWarehouseItem]
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[List["_models.BulkResponseItemOfWarehouseItem"]]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json, text/json"

        # Construct URL
        url = self.bulk_put.metadata['url']  # type: ignore
        path_format_arguments = {
            'warehouseId': self._serialize.url("warehouse_id", warehouse_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(warehouse_items, '[WarehouseItem]')
        body_content_kwargs['content'] = body_content
        request = self._client.put(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize('[BulkResponseItemOfWarehouseItem]', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    bulk_put.metadata = {'url': '/warehouses/{warehouseId}/warehouseItems'}  # type: ignore

    async def bulk_delete(
        self,
        warehouse_id: str,
        item_sk_us: List[str],
        **kwargs
    ) -> List["_models.BulkResponseItemOfString"]:
        """bulk_delete.

        :param warehouse_id:
        :type warehouse_id: str
        :param item_sk_us:
        :type item_sk_us: list[str]
        :keyword callable cls: A custom type or function that will be passed the direct response
        :return: list of BulkResponseItemOfString, or the result of cls(response)
        :rtype: list[~oscp.dataplane.models.BulkResponseItemOfString]
        :raises: ~azure.core.exceptions.HttpResponseError
        """
        cls = kwargs.pop('cls', None)  # type: ClsType[List["_models.BulkResponseItemOfString"]]
        error_map = {
            401: ClientAuthenticationError, 404: ResourceNotFoundError, 409: ResourceExistsError
        }
        error_map.update(kwargs.pop('error_map', {}))
        api_version = "2020-11-01-preview"
        content_type = kwargs.pop("content_type", "application/json")
        accept = "application/json, text/json"

        # Construct URL
        url = self.bulk_delete.metadata['url']  # type: ignore
        path_format_arguments = {
            'warehouseId': self._serialize.url("warehouse_id", warehouse_id, 'str'),
        }
        url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}  # type: Dict[str, Any]
        query_parameters['api-version'] = self._serialize.query("api_version", api_version, 'str')

        # Construct headers
        header_parameters = {}  # type: Dict[str, Any]
        header_parameters['Content-Type'] = self._serialize.header("content_type", content_type, 'str')
        header_parameters['Accept'] = self._serialize.header("accept", accept, 'str')

        body_content_kwargs = {}  # type: Dict[str, Any]
        body_content = self._serialize.body(item_sk_us, '[str]')
        body_content_kwargs['content'] = body_content
        request = self._client.delete(url, query_parameters, header_parameters, **body_content_kwargs)
        pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize('[BulkResponseItemOfString]', pipeline_response)

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized
    bulk_delete.metadata = {'url': '/warehouses/{warehouseId}/warehouseItems'}  # type: ignore
